# Generated by Django 5.0.2 on 2024-03-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='Task',
        ),
    ]
