# Generated by Django 5.0.2 on 2024-03-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0003_remove_task_tags_task_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='importance',
        ),
    ]
