# Generated by Django 5.0.2 on 2024-03-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0004_rename_priority_task_importance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
