# Generated by Django 5.0.2 on 2024-03-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0005_rename_tag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='toDoApp.tag'),
        ),
    ]
